eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8769
spring:
  application:
    name: service-zuul
zuul:
  routes:
    api-a:
      path: /api-a/**  #集群A访问地址
      serviceId: service-ribbon #集群A名，上述地址会转发给此集群
    api-b:
      path: /api-b/** #集群B访问地址
      serviceId: service-feign #集群A名，上述地址会转发给此集群